import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

import localFont from "next/font/local";

const myFont = localFont({
  src: "./fonts/TTCommonsRegular.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div>
          <Header /> {children}
        </div>
      </body>
    </html>
  );
}
