import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Sidenav from "@/components/Sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="relative ">
      <div className="flex h-[90vh]">
        <Sidenav />
        <div className="w-full overflow-y-scroll px-10">{children}</div>
      </div>
      {/* <Footer /> */}
    </main>
  );
}
